# Generated by Django 5.2.16 on 2026-08-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_add_school_tutor_video_exam_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='entranceexam',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/pdf/'),
        ),
    ]
