# Generated by Django 5.2.16 on 2026-08-16 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_entranceexam_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lectures/images/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lectures/pdf/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='lectures/audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='lectures/video/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturesG', to='app.subject')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
