# Generated by Django 5.2.16 on 2026-08-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_lectureg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['id']},
        ),
    ]
