# Generated by Django 5.2.16 on 2026-08-20 16:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Dogry jogap'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=ckeditor.fields.RichTextField(verbose_name='A varianty'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=ckeditor.fields.RichTextField(verbose_name='B varianty'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=ckeditor.fields.RichTextField(verbose_name='C varianty'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=ckeditor.fields.RichTextField(verbose_name='D varianty'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Sorag'),
        ),
    ]
