# Generated by Django 5.2.16 on 2026-08-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='results',
                to='app.subject',
            ),
        ),
    ]
