# Generated by Django 5.2.16 on 2026-08-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_examresult_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='exam',
        ),
        migrations.AddField(
            model_name='subject',
            name='exams',
            field=models.ManyToManyField(blank=True, help_text='Bu dersiň degişli bolan synaglar', related_name='subjects', to='app.entranceexam'),
        ),
    ]
