# Generated by Django 5.2.16 on 2026-08-24 04:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_subject_exam_subject_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content_text',
            field=ckeditor.fields.RichTextField(verbose_name='context_text'),
        ),
        migrations.AlterField(
            model_name='lecturetopic',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='tema_description'),
        ),
    ]
