# Generated by Django 5.2.16 on 2026-09-04 16:41

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_lecture_content_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='admission_capacity',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='applications_count',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='exam_start_at',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='content_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='context_text'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app.region', verbose_name='Etrap'),
        ),
        migrations.CreateModel(
            name='SpecialtyRegionAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_capacity', models.IntegerField(default=0, verbose_name='Kabul edilmeli talyp sany')),
                ('applications_count', models.IntegerField(default=0, verbose_name='Tabşyrylanlaryň sany')),
                ('exam_start_at', models.DateTimeField(blank=True, null=True, verbose_name='Synagyň başlaýan wagty')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_admissions', to='app.region')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_admissions', to='app.specialty')),
            ],
            options={
                'ordering': ['specialty', 'region'],
                'unique_together': {('specialty', 'region')},
            },
        ),
    ]
