# Generated by Django 5.2.16 on 2026-09-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_region_remove_specialty_admission_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Kolay'), ('medium', 'Orta'), ('hard', 'Kyn')], default='medium', help_text='Soragyň aýdymlıklygy: Kolay, Orta, Kyn', max_length=10, verbose_name='Kynlyk derejesi'),
        ),
    ]
