# Generated by Django 5.2.16 on 2026-09-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='duration_seconds',
            field=models.IntegerField(default=0, verbose_name='Testiň dowamlylygy (sekunt)'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='incorrect_count',
            field=models.IntegerField(default=0, verbose_name='Ýalňyş jogap sany'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='correct_count',
            field=models.IntegerField(default=0, verbose_name='Dogry jogap sany'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Ball (%)'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='Jemi sorag sany'),
        ),
    ]
