# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_examresult_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='formula',
            field=models.CharField(blank=True, help_text='Soragda kimyawy formula bar (mesele H2SO4). Awomatik tapylýar.', max_length=50, null=True, verbose_name='Kimyawy formula'),
        ),
    ]