# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_question_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, help_text='Soragyň kysa ady (mesele: Nyutonyň 1-nji kanuny). Awomatik tapylýar.', max_length=200, null=True, verbose_name='Soragyň ady'),
        ),
    ]