# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='lectures', to='app.school', verbose_name='Mekdep'),
        ),
    ]