# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_lecture_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Soragyň dersdäki taribi (1, 2, 3...).', verbose_name='Sorag sanawy (order)'),
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['subject', 'order', 'id']},
        ),
    ]