# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='questions_pdf',
            field=models.FileField(blank=True, help_text='Soraglaryň PDF faýly (klasa we ders boýunça)', null=True, upload_to='subjects/questions/', verbose_name='Soraglar PDF'),
        ),
        migrations.AddField(
            model_name='subject',
            name='answers_pdf',
            field=models.FileField(blank=True, help_text='Dogry jogaplaryň PDF faýly (klasa we ders boýunça)', null=True, upload_to='subjects/answers/', verbose_name='Jogaplar PDF'),
        ),
    ]