# Generated by Django 5.2.16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_subject_pdfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubjectPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_pdf', models.FileField(blank=True, help_text='Mekdep we ders boýunça leksiýa PDF faýly', null=True, upload_to='school_subject_lectures/pdf/', verbose_name='Leksiýa PDF')),
                ('questions_pdf', models.FileField(blank=True, help_text='Mekdep we ders boýunça soraglar PDF faýly', null=True, upload_to='school_subject_lectures/questions/', verbose_name='Soraglar PDF')),
                ('answers_pdf', models.FileField(blank=True, help_text='Mekdep we ders boýunça jogaplar PDF faýly', null=True, upload_to='school_subject_lectures/answers/', verbose_name='Jogaplar PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_pdfs', to='app.school', verbose_name='Mekdep')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_pdfs', to='app.subject', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Mekdep-Ders PDF',
                'verbose_name_plural': 'Mekdep-Ders PDF faýllary',
                'ordering': ['school', 'subject'],
                'unique_together': {('school', 'subject')},
            },
        ),
    ]