# Generated by Django 5.2.16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0027_school_subject_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Mesele: 9-A, 10-B, 11-C', max_length=50, verbose_name='Klas ady')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='app.school', verbose_name='Mekdep')),
                ('subjects', models.ManyToManyField(blank=True, related_name='classes', to='app.subject', verbose_name='Dersler')),
            ],
            options={
                'verbose_name': 'Klas',
                'verbose_name_plural': 'Klaslar',
                'ordering': ['school', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='schoolsubjectpdf',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='Bu faýl kamyň klasyna bagly (ýoksa mekdepýň umumy faýly)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_pdfs', to='app.schoolclass', verbose_name='Klas'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolsubjectpdf',
            unique_together={('school', 'school_class', 'subject')},
        ),
    ]